### PR TITLE
Close out project

### PR DESCRIPTION
**Pull request by tysongach**
I had to do a PR since Issues are not enabled for this repo…

Now that Bourbon is LibSass-compatible [as of v4.2](https://github.com/thoughtbot/bourbon/releases/tag/v4.2.0), any chance we can close out this fork and remove [`bourbon-libsass`](https://www.npmjs.com/package/bourbon-libsass) from the npm registry ([`npm unpublish`](https://docs.npmjs.com/cli/unpublish))? I’d like to make sure we don’t confuse people and point them in multiple directions by having forks like this.

Thanks!

### CODE REVIEW

**Comment by tysongach** [comment]
Ping @jamesmenera

**Comment by tysongach** [comment]
Ping @jamesmenera

**Comment by jamesmenera** [comment]
@tysongach sorry I just finally read this will unpublished thanks!

**Comment by tysongach** [comment]
@jamesmenera Thank you!

**Comment by tysongach** [comment]
@jamesmenera Any update on getting this removed from npm?

**Pull request closed without merging**
